version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.8
    working_directory: /go/src/github.com/ktnyt/echo-rest
    steps:
      - checkout
      - run: go get -d -t -v ./...
      - run: go test
